### PR TITLE
remove 'num-availability-zones' flag for template nodepool command

### PR DESCRIPTION
**Pull request by alex-dabija**
Towards: https://github.com/giantswarm/giantswarm/issues/15826 .

### CODE REVIEW

**Comment by njuettner** [comment]
I created a PR https://github.com/giantswarm/github/pull/169, after merging GH action will create another PR inside this repo to align files (mostly replacing architect-orb). This will fix CI from failing.

**Comment by njuettner** [comment]
should be good to go 👍🏻

**Review by marians — APPROVED** [review]

**Comment by whites11** [comment]
I am super-confused right now. Isn't this ticket asking to do exactly the opposite of what's been done in this PR? 
https://github.com/giantswarm/giantswarm/issues/16667

**Comment by marians** [comment]
@whites11 This PR here is removing a flag that currently has no function. https://github.com/giantswarm/giantswarm/issues/16667 is about bringing back the function and flag.

This is only weird when happening almost at the same time or not in the right order.  (Nobody knew somebody/you would jump at it right away.)

**Pull request merged**
