### PR TITLE
Add minimal support for templating CAPZ clusters

### PR DESCRIPTION
**Pull request by AndiDog**
### What does this PR do?

Towards https://github.com/giantswarm/roadmap/issues/525

### What is the effect of this change to users?

None, since cluster templating for CAPZ wasn't a supported feature before

### What does it look like?

This minimal command now works:

```
kubectl gs template cluster --provider capz --organization testing --name bam --region westeurope --azure-subscription-id 00000000-0000-0000-0000-000000000000
```

### Any background context you can provide?

Mainly to make our "Create a workload cluster" documentation consistent, since I'm currently working on that (https://github.com/giantswarm/roadmap/issues/2393)

### Should this change be mentioned in the release notes?

- [x] CHANGELOG.md has been updated

### Is this a breaking change?

No

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Review by bavarianbidi — CHANGES_REQUESTED** [review]
Coming from https://gigantic.slack.com/archives/C02FJACQ3D4/p1678256339790879
in https://github.com/giantswarm/kubectl-gs/pull/1038 the `CAPZ` template feature got implemented in `kubectl-gs` (public doc: https://docs.giantswarm.io/getting-started/capz-cluster-creation/)

The main reason for doing the implementation that way was not having a second place where all the possible flags has to be maintained.

Maybe something which has to be discussed again?!

**Comment by AndiDog** [comment]
@bavarianbidi (and ex @giantswarm/team-clippy) we discussed in KaaS Sync that anyhow a new command `kubectl gs create cluster` will totally replace the whole manually-crafted code. With that, we said that merging _this here_ for the short term is fine, since we won't work on it anymore and at least I can make the commands in our documentation the same for now. Let me know if you have concerns or a LGTM.

**Comment by uvegla** [comment]
If not too much trouble, could you please hook it into `gitops add base` command: https://github.com/giantswarm/kubectl-gs/blob/be802a0f2213f69266645e69a96d02580e16a03b/cmd/gitops/add/base/runner.go#L92-L103 🙏🏻 

If the conventions were followed it should be fairly straightforward.

**Comment by bavarianbidi** [comment]
> > The main reason for doing the implementation that way was not having a second place where all the possible flags has to be maintained.
> > Maybe something which has to be discussed again?!
> 
> I had the same feeling. Too many ways to template stuff, and especially all the CLI params are not maintainable. Let me bring this up in KaaS sync, maybe.

sure, i wont block this but then let's drop the `template` implementation again (introduced in https://github.com/giantswarm/kubectl-gs/pull/1038) + remove the existing public documentation https://docs.giantswarm.io/getting-started/capz-cluster-creation/ as well.

**Comment by AndiDog** [comment]
Thanks for the input 👍. I've implemented the suggestions.

@uvegla `kubectl gs gitops add base --provider capz --region westeurope --azure-subscription-id BLABLA` now works.

@bavarianbidi `--cluster-config`/`--default-app-config` templating option code is removed.

**Review by bavarianbidi — APPROVED** [review]

**Pull request merged**
