### PR TITLE
Display `SERVICE PRIORITY` column in `get clusters` output

### PR DESCRIPTION
**Pull request by kuosandys**
Towards https://github.com/giantswarm/giantswarm/issues/22332.

This PR adds the `SERVICE PRIORITY` column to the table output of the `get clusters` command:
Screen Shot 2022-06-08 at 12 18 20

---

As the creator of a pull request, please consider:

- [x] Describe the goal you are trying to accomplish here, above the line.
- [x] Add a user-friendly description of your change to `CHANGELOG.md`.
- [x] Provide a link to the issue you are solving or working towards, if available.
- [x] Request SIG UX for review. They care about almost all user-facing changes.
- [ ] Update the public [kubectl-gs documentation](https://docs.giantswarm.io/ui-api/kubectl-gs/) to reflect the changes here.
- [x] add the `breaking-change` label to the PR if the change you are making changes the existing behaviour. Examples: removal of a flag, removal of a command, change of a default value. (Such changes should be released with a **major version** bump.)

Feel free to remove this checklist when done.

### CODE REVIEW

**Review by pipo02mix — APPROVED** [review]
Did not check code, but the UI seems good to me

**Comment by kuosandys** [comment]
> I'm on the fence here with regard to one detail. I know we display other values like this in UPPERCASE, so it's consistent to do it for this column, too. On the other hand I hope that people understand that the actual label value has to be used in lowercase. Would it be appropriate to print that column in the original case?

That's a good point. I think printing it in the same letter casing as the expected label value would prevent adding to mental load. I'll make the changes 👍

**Comment by anvddriesch** [comment]
Should we display `n/a` at all? I was personally expecting it to be `highest` when it's not set since that is the de facto priority of the cluster. Or do  we want to make clear that it has not been set?

**Comment by marians** [comment]
I think it's good as it is. If we display `highest` here if the label is not set, then users will have a harder time finding clusters where the label is not used.

Giant Swarm staff should know how to interpret the label not being set.

**Review by marians — APPROVED** [review]

**Comment by kuosandys** [comment]
> Should we display `n/a` at all? I was personally expecting it to be `highest` when it's not set since that is the de facto priority of the cluster. Or do we want to make clear that it has not been set?

I based it off of how we've currently implemented it in happa: if the service priority label is not set, we don't display the label - I guess the equivalent here is the `n/a` value. I thought it might be a bit confusing to see a value displayed that isn't set, even if `highest` service priority is assumed for handling clusters without the label, and maybe seeing the missing value will prompt users to set a service priority 🙃

**Comment by anvddriesch** [comment]
Sure. It is also possible that the users don't want to treat unset clusters as if they have highest priority :smile:

**Review by anvddriesch — APPROVED** [review]

**Pull request merged**
