### PR TITLE
Parse new Release CRs

### PR DESCRIPTION
**Pull request by pipo02mix**
Since we changed the format of the releases (now they are CRs) I added the properties to the structs

### CODE REVIEW

**Comment by pipo02mix** [comment]
New format
```
apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
  annotations:
    giantswarm.io/docs: https://docs.giantswarm.io/reference/cp-k8s-api/releases.release.giantswarm.io/
  name: v11.1.1
spec:
  state: wip
  date: 2020-03-17T12:00:00Z
  apps:
  - name: cert-exporter
    version: 1.2.1
  - name: cert-manager
    componentVersion: 0.9.0
    version: 1.0.6
  - name: chart-operator
    version: 0.12.1
  - name: cluster-autoscaler
    componentVersion: 1.16.2
    version: 1.1.4
  - name: coredns
    componentVersion: 1.6.5
    version: 1.1.7
  - name: external-dns
    componentVersion: 0.5.18
    version: 1.2.0
  - name: kiam
    componentVersion: 3.5.0
    version: 1.2.1
  - name: kube-state-metrics
    componentVersion: 1.9.2
    version: 1.0.4
  - name: metrics-server
    componentVersion: 0.3.3
    version: 1.0.0
  - name: net-exporter
    version: 1.5.1
  - name: node-exporter
    componentVersion: 0.18.1
    version: 1.2.0
  components:
  - name: app-operator
    version: 1.0.0
  - name: aws-operator
    version: 8.2.1
  - name: cert-operator
    version: 0.1.0
  - name: cluster-operator
    version: 2.1.5
  - name: kubernetes
    version: 1.16.3
  - name: containerlinux
    version: 2191.5.0
  - name: calico
    version: 3.10.1
  - name: etcd
    version: 3.3.17
---
apiVersion: release.giantswarm.io/v1alpha1
kind: Release
metadata:
...
```
For some reason it still complaining 
```
Error: error unmarshaling JSON: json: cannot unmarshal object into Go value of type []gsrelease.Release
panic: "{\"kind\":\"unknown\",\"annotation\":\"error unmarshaling JSON: json: cannot unmarshal object into Go value of type []gsrelease.Release\",\"stack\":[{\"file\":\"/Users/fernando/go/src/github.com/giantswarm/kubectl-gs/pkg/gsrelease/release.go\",\"line\":177},{\"file\":\"/Users/fernando/go/src/github.com/giantswarm/kubectl-gs/pkg/gsrelease/release.go\",\"line\":75},{\"file\":\"/Users/fernando/go/src/github.com/giantswarm/kubectl-gs/cmd/template/cluster/flag.go\",\"line\":111},{\"file\":\"/Users/fernando/go/src/github.com/giantswarm/kubectl-gs/cmd/template/cluster/runner.go\",\"line\":34},{\"file\":\"/Users/fernando/go/src/github.com/giantswarm/kubectl-gs/main.go\",\"line\":47}]}"
```

Please @corest if you can take a look

**Comment by corest** [comment]
There is no more list with releases. Now it is a multi-document file. And that's whole new story on how to parse this

**Comment by corest** [comment]
I've fixed it with a different yaml library. But waiting for feedback for our go gods in dev channel

**Comment by corest** [comment]
It should be fine to proceed.

**Pull request merged**
