### PR TITLE
Adding WC related stuff

### PR DESCRIPTION
**Pull request by ljakimczuk**
## Description

Command introduced in this PR created Workload Cluster-related directory structure in the GitOps repository pointed by the user. It can create structure with or without the cluster definition, in case user does not want to keep in in the repository yet for example. The command gives a chance to pass user values as well to customize the cluster and its default apps.

**Note:** I realize eventually this command should be even more configurable, i.e. user should be able to influence Kustomization CR options, or we should account for `mapi` vs `out-of-band`, but let's stick to a simpler version for now, to workout a common way of working with directories.

#### Existence of the base

Command does not create cluster definition on its own, instead it relies on the base that must be pre-configured by the user. When base argument is not provided, command is limited to creating the directory structure without cluster definition.

#### User config layer is free to use

It is assumed that user follows the GS recommendation towards base configuration, and hence uses only the `.spec.config` layer of configuration, leaving `.spec.userconfig` free to use to the command.

## ToDos

- [x] update `workload-clusters/kustomization.yaml` when adding new WC

## Examples

1. Create the structure only 

```sh
$ kubectl gs gitops add wc \
--name mywc \
--local-path /tmp/mygitopsrepo \
--management-cluster mymc \
--organization myorg \
--repository-name mygitopsrepo  \
--dry-run

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mymc-clusters-mywc
  namespace: default
spec:
  interval: 1m
  path: "./management-clusters/mymc/organizations/myorg/workload-clusters/mywc"
  postBuild:
    substitute:
      cluster_name: "mywc"
      organization: "myorg"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: mygitopsrepo
  timeout: 2m

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/apps
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster
```
2. Create the structure and cluster from base, without customizing it

```sh
$ kubectl gs gitops add wc \
--name mywc \
--local-path /tmp/mygitopsrepo \
--management-cluster mymc \
--organization myorg \
--repository-name mygitopsrepo \
--base bases/cluster/capo \
--cluster-release 0.13.0 \
--default-apps-release 0.6.0 \
--dry-run

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mymc-clusters-mywc
  namespace: default
spec:
  interval: 1m
  path: "./management-clusters/mymc/organizations/myorg/workload-clusters/mywc"
  postBuild:
    substitute:
      cluster_name: "mywc"
      organization: "myorg"
      cluster_release: "0.13.0"
      default_apps_release: "0.6.0"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: mygitopsrepo
  timeout: 2m

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/apps
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
resources:
  - ../../../../../../../bases/cluster/capo
```

3. Create the structure, cluster from base and customize it with some user values

```sh
$ kubectl gs gitops add wc \
--name mywc \
--local-path /tmp/mygitopsrepo \
--management-cluster mymc \
--organization myorg \
--repository-name mygitopsrepo \
--base bases/cluster/capo \
--cluster-release 0.13.0 \
--default-apps-release 0.6.0 \
--cluster-user-config /tmp/myclusteruserconfig.yaml \
--default-apps-user-config /tmp/mydefaultappsuserconfig.yaml \
--dry-run

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mymc-clusters-mywc
  namespace: default
spec:
  interval: 1m
  path: "./management-clusters/mymc/organizations/myorg/workload-clusters/mywc"
  postBuild:
    substitute:
      cluster_name: "mywc"
      organization: "myorg"
      cluster_release: "0.13.0"
      default_apps_release: "0.6.0"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: mygitopsrepo
  timeout: 2m

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/apps
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster
/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster/cluster_userconfig.yaml
apiVersion: v1
data:
  values: |
    someKey: someValue
    anotherKey:
      nestedKey: nestedValue
      nestedArray:
        - value1
        - value2
kind: ConfigMap
metadata:
  name: mywc-userconfig
  namespace: org-myorg

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster/default_apps_userconfig.yaml
apiVersion: v1
data:
  values: |
    app1Key:
      app1NestedKey: app1Value
      app1NestedArray:
      - val1
      - val2
kind: ConfigMap
metadata:
  name: mywc-default-apps-userconfig
  namespace: org-myorg

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
patchesStrategicMerge:
  - patch_cluster_userconfig.yaml
  - patch_default_apps_userconfig.yaml
resources:
  - ../../../../../../../bases/cluster/capo
  - cluster_userconfig.yaml
  - default_apps_userconfig.yaml

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster/patch_cluster_userconfig.yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}
  namespace: org-${organization}
spec:
  userConfig:
    configMap:
      name: mywc-userconfig
      namespace: org-myorg

/tmp/mygitopsrepo/management-clusters/mymc/organizations/myorg/workload-clusters/mywc/cluster/patch_default_apps_userconfig.yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-default-apps
  namespace: org-${organization}
spec:
  userConfig:
    configMap:
      name: mywc-default-apps-userconfig
      namespace: org-myorg
```

### CODE REVIEW

**Comment by MarcelMue** [comment]
I know this is kind a bit out of left field but I believe this could have some nice tests. You could use e.g. a golden file to compare templated output to in a testcase. See e.g. this testcase for a rough example: https://github.com/giantswarm/aws-operator/blob/877773e97b68730673553a424f12a1fb56dbc339/service/controller/resource/tcnpf/create_test.go#L43-L74

**Comment by ljakimczuk** [comment]
@MarcelMue absolutely agree, I haven't added any tests yet because I still kind of feel I'm trying to figure out the right way of implementing this stuff, especially now when I finally got to the WC part, because here things can get complicated a bit. I mean we already consider some number of scenarios in the `gitops-template`, each with its own, similar, but sometimes slightly different requirements towards files or directories, etc. But don't worry, before we merge anything to the `main` branch, I will do my best to add nice tests, including comparison of templated output.

**Comment by kubasobon** [comment]
The code looks good from the first look

**Comment by kubasobon** [comment]
image
:heart:

**Review by piontec — APPROVED** [review]
checked teh examples only, but they look all good!

**Pull request merged**
