### PR TITLE
enable unsafe login for older clusters in default namespace

### PR DESCRIPTION
**Pull request by anvddriesch**
This PR is not supposed to be merged
Towards https://github.com/giantswarm/giantswarm/issues/19961

### CODE REVIEW

**Review by axbarsan — APPROVED** [review]
https://github.com/giantswarm/kubectl-gs/blob/13fda5b80e2c391f2618f35b7ca52b409cbbc835/cmd/login/clientcert.go#L454

I think this needs some love, too

**Comment by anvddriesch** [comment]
You are right! :) I'll change it to display the version we define.

**Comment by TheoBrigitte** [comment]
Tried this with a 13.2.0 cluster on gauss and hit a timeout

```
+ kubectl gs login --certificate-ttl 24h --certificate-group system:masters --insecure-namespace --workload-cluster q6w4t gauss
Switched to context 'gs-gauss'.
You are logged in to the management cluster of installation 'gauss'.
I1201 19:33:29.910571  134215 request.go:621] Throttling request took 1.200740562s, request: GET:https://g8s.gauss.eu-west-1.aws.gigantic.io/apis/cluster.x-k8s.io/v1alpha3/namespaces/org-eric/clusters?labelSelector=cluster.x-k8s.io%2Fcluster-name%3Dq6w4t
Error: Credential retrieval timed out: failed to get the client certificate credential on time
```

**Comment by anvddriesch** [comment]
Interesting. It worked for me with a 15.0.0 cluster. However, I guess I need to test more. Thank you for the heads up!

**Comment by anvddriesch** [comment]
So the `certConfig` gets created. However, `cert-operator` is not happy.
```
{"caller":"github.com/giantswarm/operatorkit/controller/controller.go:444","controller":"cert-operator","event":"update","level":"debug","loop":"526973","message":"reconciling object","object":"/apis/core.giantswarm.io/v1alpha1/namespaces/default/certconfigs/ui73r-9307df3923b1e633","time":"2021-12-02T10:48:17.071967+00:00","version":"363991459"}
{"caller":"github.com/giantswarm/operatorkit/controller/controller.go:459","controller":"cert-operator","event":"update","level":"debug","loop":"526973","message":"finding resource set","object":"/apis/core.giantswarm.io/v1alpha1/namespaces/default/certconfigs/ui73r-9307df3923b1e633","time":"2021-12-02T10:48:17.072016+00:00","version":"363991459"}
{"caller":"github.com/giantswarm/operatorkit/controller/controller.go:463","controller":"cert-operator","event":"update","level":"debug","loop":"526973","message":"did not find resource set","object":"/apis/core.giantswarm.io/v1alpha1/namespaces/default/certconfigs/ui73r-9307df3923b1e633","time":"2021-12-02T10:48:17.072051+00:00","version":"363991459"}
{"caller":"github.com/giantswarm/operatorkit/controller/controller.go:464","controller":"cert-operator","event":"update","level
```

**Comment by anvddriesch** [comment]
Figured it out! :) The reason was that the older `cert-operator` relies on the deprecetad `versionBundle` field which was missing from our `certConfig`. I added this so now it should not be a problem anymore.

**Comment by TheoBrigitte** [comment]
Works with a `13.2.0` cluster on `gauss`

```
$ k gs get clusters -A
NAMESPACE        NAME    AGE     CONDITION   RELEASE            ORGANIZATION   DESCRIPTION
default          q6w4t   19h     CREATED     13.2.0             giantswarm     theo test

$ kubectl gs login --certificate-ttl 24h --certificate-group system:masters --insecure-namespace --workload-cluster q6w4t gauss
Switched to context 'gs-gauss'.
You are logged in to the management cluster of installation 'gauss'.
I1202 13:43:54.779503  220735 request.go:621] Throttling request took 1.000554696s, request: GET:https://g8s.gauss.eu-west-1.aws.gigantic.io/apis/cluster.x-k8s.io/v1alpha3/namespaces/org-eric/clusters?labelSelector=cluster.x-k8s.io%2Fcluster-name%3Dq6w4t

Created client certificate for workload cluster 'q6w4t'.
A new kubectl context has been created named 'gs-gauss-q6w4t' and selected. To switch back to this context later, use this command:

  kubectl config use-context gs-gauss-q6w4t
```

**Review by TheoBrigitte — APPROVED** [review]
Approved as user

**Review by kuosandys — APPROVED** [review]
..Let's merge?

**Pull request merged**
