### PR TITLE
Switched from exp to non-exp apiVersion for azure `MachinePools`

### PR DESCRIPTION
**Pull request by whites11**
Towards: https://github.com/giantswarm/giantswarm/issues/22631

This PR fixes `kubectl gs get nodepool` command for azure clusters >= 17.1.0.
And breaks if for clusters < 17.1.0 (currently  clusters)

---

As the creator of a pull request, please consider:

- [x] Describe the goal you are trying to accomplish here, above the line.
- [x] Add a user-friendly description of your change to `CHANGELOG.md`.
- [x] Provide a link to the issue you are solving or working towards, if available.
- [ ] Request SIG UX for review. They care about almost all user-facing changes.
- [ ] Update the public [kubectl-gs documentation](https://docs.giantswarm.io/ui-api/kubectl-gs/) to reflect the changes here.
- [ ] add the `breaking-change` label to the PR if the change you are making changes the existing behaviour. Examples: removal of a flag, removal of a command, change of a default value. (Such changes should be released with a **major version** bump.)

Feel free to remove this checklist when done.

### CODE REVIEW

**Comment by whites11** [comment]
@giantswarm/team-rainbow go tests are passing locally and failing on circle CI. Can you please help?

**Review by anvddriesch — APPROVED** [review]
LGTM

**Review by njuettner — APPROVED** [review]
lgtm

**Comment by marians** [comment]
> And breaks if for clusters < 17.1.0 (currently clusters)

Could you please clarify this a bit more?

**Comment by whites11** [comment]
@marians are you ok with me merging this PR?

**Comment by marians** [comment]
@whites11 I'm worried about breaking functionality for users. Normally we would try to adapt the implementation to work with both old and new clusters. I can't judge the impact though, as I don't know what percentage is still older than 17.1.0.

**Pull request merged**
