### PR TITLE
[Gitops] Introduce `add encryption` command

### PR DESCRIPTION
**Pull request by ljakimczuk**
## Description

Towards: https://github.com/giantswarm/roadmap/issues/1141

The command helps user to configure the SOPS-based encryption for his GitOps repository. In particular it supports the following:

* generating SOPS key pair. Exporting existing keys from the keychain is not supported at the moment.
* saving public and private keys to their respective locations. The command runs SOPS decryption underneath for the `MC_NAME.gpgkey.enc.yaml` and `WC_NAME.gpgkey.enc.yaml` Secrets kept in the repository **with an assumption user has the right private key already loaded to his keychain. If not, updating the file will not be possible.**
* patching `MC_NAME.yaml` and `WC_NAME.yaml` Kustomization CRs respectively with the `.spec.decryption` field.
* configuring `.sops.yaml` file with the new rule if it doesn't already exist.

In addition this PR introduces:

* tests re-organization, don't be afraid by the number of lines added as most of it comes as the result of moving golden files between dirs. This had to be done to aid readability. 
* modifier package re-organization, so far it has been part of the creator package, but I graduated it to its own being. Also dropped JMESPath and JSONPatch there in favor of working with the `map[string]interface{}`. I think JMESPath / JSONPatch may turn themselves usefull when we find out more modifier-wise operations, but it turned out there ain't much of them for the basic commands I implemented.
* changes to `add mc` command and introducing `--gen-master-key` flag there, so that the "master" encryption key can be generated already at the time of adding a new management cluster. If not done then, it still can be added later as shown in the below examples.
* `init` command. I realized that while we have a nice support for adding bunch of layers to the repository, we do not have any command taking care of the initial stuff in the repository root, like `management-clusters` directory or `.sops.yaml` file, so I added it.
* `structure` uses now a single `StructureConfig` instead of multiple configs for each layer. This is mostly to decrease the data number as some fields were repeated between previous structs. This is not something of great importance, but something I wanted to improve, and what I hope aids readability.
* finally I added a run for post modifiers to `creator`'s package `print()` function, so that when user runs command with the `dry-run` flag, he now gets not only what will be created by the command, but also what and how will be modified by it. This is to show him the full picture, and also to predict possible problems.

## Important

The command takes a bit different approach on SOPS keys naming in comparison to what we have in the `gitops-template` repository. While freedom is still given to the users willing to configure the repository on their own, the automation uses the following pattern for naming the keys in the `.sops.keys` directory and in the `(MC_NAME | WC_NAME).gpgkey.enc.yaml` secret:

`(MC_NAME | WC_NAME).FINGERPRINT.asc`

This way it's much easier to identify what's being used and where.

### Add master key, or just another Management Cluster key

```sh
$ kubectl gs gitops add enc --generate \
--management-cluster demomc \
--local-path /tmp/myrepo \
--dry-run

/tmp/myrepo/management-clusters/demomc/.sops.keys/demomc.d2c54e564814b948f305e515002086c0d12d3350.asc
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GopenPGP 2.4.8
Comment: https://gopenpgp.org

xjMEYvPlvhYJKwYBBAHaRw8BAQdAnS1P4amOeE0eBmabcPEkzrB49XMRdudNrHAG
clKnJY7NEmRlbW9tYyBGbHV4IG1hc3RlcsKMBBMWCAA+BQJi8+W+CZAAIIbA0S0z
UBYhBNLFTlZIFLlI8wXlFQAghsDRLTNQAhsDAh4BAhkBAwsJBwIVCAMWAAICIgEA
AJZ8AP9DG/T//JdSxWkY149kqzfCWWEbWRUBJQ8uHVbz8MHn+gD8D2SAgyI7d3rN
JMCvlF+sli+5wdSIQAksclBYJxXCagnOOARi8+W+EgorBgEEAZdVAQUBAQdAcCr4
ObWFU13u9zCHF0NwrjdZQ0HPUMBwcztyKa5/Qw8DAQoJwngEGBYIACoFAmLz5b4J
kAAghsDRLTNQFiEE0sVOVkgUuUjzBeUVACCGwNEtM1ACGwwAAFyOAQCbmn3QYm83
z2KW/QdCMQnPesSqEo3VievmM3FO3Ua4aAEA8Z+/VrrP+MajZP396HcJsmHJ1lZ5
F7l/8wmcRIMNpQs=
=Zohj
-----END PGP PUBLIC KEY BLOCK-----

/tmp/myrepo/management-clusters/demomc/demomc.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demomc-gitops
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-master
  interval: 1m
  path: ./management-clusters/demomc
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: gitops-demo
  timeout: 2m

/tmp/myrepo/.sops.yaml
creation_rules:
- encrypted_regex: ^(data|stringData)$
  path_regex: management-clusters/demomc/secrets/.*\.enc\.yaml
  pgp: d2c54e564814b948f305e515002086c0d12d3350

/tmp/myrepo/management-clusters/demomc/secrets/demomc.gpgkey.enc.yaml
apiVersion: v1
data:
  demomc.d2c54e564814b948f305e515002086c0d12d3350.asc: LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQpWZXJzaW9uOiBHb3BlblBHUCAyLjQuOApDb21tZW50OiBodHRwczovL2dvcGVucGdwLm9yZwoKeFZnRVl2UGx2aFlKS3dZQkJBSGFSdzhCQVFkQW5TMVA0YW1PZUUwZUJtYWJjUEVrenJCNDlYTVJkdWROckhBRwpjbEtuSlk0QUFQNG9hWmRqZjNoM01RNW11L3JHZ1lyVStXQ3RjdjluWmNBaWY4UGJmQ1EyU0JGV3pSSmtaVzF2CmJXTWdSbXgxZUNCdFlYTjBaWExDakFRVEZnZ0FQZ1VDWXZQbHZnbVFBQ0NHd05FdE0xQVdJUVRTeFU1V1NCUzUKU1BNRjVSVUFJSWJBMFMwelVBSWJBd0llQVFJWkFRTUxDUWNDRlFnREZnQUNBaUlCQUFDV2ZBRC9ReHYwLy95WApVc1ZwR05lUFpLczN3bGxoRzFrVkFTVVBMaDFXOC9EQjUvb0EvQTlrZ0lNaU8zZDZ6U1RBcjVSZnJKWXZ1Y0hVCmlFQUpMSEpRV0NjVndtb0p4MTBFWXZQbHZoSUtLd1lCQkFHWFZRRUZBUUVIUUhBcStEbTFoVk5kN3Zjd2h4ZEQKY0s0M1dVTkJ6MURBY0hNN2NpbXVmME1QQXdFS0NRQUEvMEx6U2Q3K2VUWTlXQWwrS3dnQ0hkdmNBTjZhU1FzSwpUaWw5N2M2RDFiVUFEci9DZUFRWUZnZ0FLZ1VDWXZQbHZnbVFBQ0NHd05FdE0xQVdJUVRTeFU1V1NCUzVTUE1GCjVSVUFJSWJBMFMwelVBSWJEQUFBWEk0QkFKdWFmZEJpYnpmUFlwYjlCMEl4Q2M5NnhLb1NqZFdKNitZemNVN2QKUnJob0FRRHhuNzlXdXMvNHhxTmsvZjNvZHdteVljbldWbmtYdVgvekNaeEVndzJsQ3c9PQo9dXNPegotLS0tLUVORCBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQ==
kind: Secret
metadata:
  name: sops-gpg-master
```

### Configure encryption for organization with a custom path

```sh
$ kubectl gs gitops add enc --generate \
--management-cluster demomc \
--organization demoorg \
--target credentials \
--local-path /tmp/myrepo \
--dry-run

/tmp/myrepo/management-clusters/demomc/.sops.keys/demomc.90f5a85b90ae65ed25faf800d70bb5672db74a1b.asc
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GopenPGP 2.4.8
Comment: https://gopenpgp.org

xjMEYvPmNBYJKwYBBAHaRw8BAQdA5A2O17XFdUbowFyT6MGhREILYRJ/iwPtPPqE
aajloubNH2RlbW9vcmcgT3JnYW5pemF0aW9uIGVuY3J5cHRpb27CjAQTFggAPgUC
YvPmNAmQ1wu1Zy23ShsWIQSQ9ahbkK5l7SX6+ADXC7VnLbdKGwIbAwIeAQIZAQML
CQcCFQgDFgACAiIBAACUlwD/YqVCIXRlVtTGEDYhbdUSnXnm+5Eb5fFjZ2mkuYyi
fXQA/0Sn9hCkYCCwKZipCXTpS9ZOsWJJU0ykkmt9LKaHdj4EzjgEYvPmNBIKKwYB
BAGXVQEFAQEHQOKCj4qM2fIUviKaGVDwlzPm7A6FxT9j8RcAWfyVfjRMAwEKCcJ4
BBgWCAAqBQJi8+Y0CZDXC7VnLbdKGxYhBJD1qFuQrmXtJfr4ANcLtWctt0obAhsM
AACOtgD9EM5deNBLsfTe/SBVdOUe11G19dXaGxhjSKJ3v0aM2zgA/RL8fortiKiT
3iFLaimVAP8hAfk7xxecK/D+U4bMQfkJ
=5RPZ
-----END PGP PUBLIC KEY BLOCK-----

/tmp/myrepo/management-clusters/demomc/demomc.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demomc-gitops
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-master
  interval: 1m
  path: ./management-clusters/demomc
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: gitops-demo
  timeout: 2m

/tmp/myrepo/.sops.yaml
creation_rules:
- encrypted_regex: ^(data|stringData)$
  path_regex: management-clusters/demomc/organizations/demoorg/credentials/.*\.enc\.yaml
  pgp: 90f5a85b90ae65ed25faf800d70bb5672db74a1b

/tmp/myrepo/management-clusters/demomc/secrets/demomc.gpgkey.enc.yaml
apiVersion: v1
data:
  demomc.90f5a85b90ae65ed25faf800d70bb5672db74a1b.asc: LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQpWZXJzaW9uOiBHb3BlblBHUCAyLjQuOApDb21tZW50OiBodHRwczovL2dvcGVucGdwLm9yZwoKeFZnRVl2UG1OQllKS3dZQkJBSGFSdzhCQVFkQTVBMk8xN1hGZFVib3dGeVQ2TUdoUkVJTFlSSi9pd1B0UFBxRQphYWpsb3VZQUFQOVZMK3AxcXY5aXUwUGZCbFllWXRQK2cwaDVHRlBSZUw4Mi9qMzcvcTl2dkJKeXpSOWtaVzF2CmIzSm5JRTl5WjJGdWFYcGhkR2x2YmlCbGJtTnllWEIwYVc5dXdvd0VFeFlJQUQ0RkFtTHo1alFKa05jTHRXY3QKdDBvYkZpRUVrUFdvVzVDdVplMGwrdmdBMXd1MVp5MjNTaHNDR3dNQ0hnRUNHUUVEQ3drSEFoVUlBeFlBQWdJaQpBUUFBbEpjQS8yS2xRaUYwWlZiVXhoQTJJVzNWRXAxNTV2dVJHK1h4WTJkcHBMbU1vbjEwQVA5RXAvWVFwR0FnCnNDbVlxUWwwNlV2V1RyRmlTVk5NcEpKcmZTeW1oM1krQk1kZEJHTHo1alFTQ2lzR0FRUUJsMVVCQlFFQkIwRGkKZ28rS2pObnlGTDRpbWhsUThKY3o1dXdPaGNVL1kvRVhBRm44bFg0MFRBTUJDZ2tBQVA5WWdVWjY2R01Nai91VQpzSldMMCtSMjZQY1ZnQXpuNmwrbVRLUnZzczFiQUJLWnduZ0VHQllJQUNvRkFtTHo1alFKa05jTHRXY3R0MG9iCkZpRUVrUFdvVzVDdVplMGwrdmdBMXd1MVp5MjNTaHNDR3d3QUFJNjJBUDBRemwxNDBFdXg5Tjc5SUZWMDVSN1gKVWJYMTFkb2JHR05Jb25lL1JvemJPQUQ5RXZ4K2l1MklxSlBlSVV0cUtaVUEveUVCK1R2SEY1d3I4UDVUaHN4QgorUWs9Cj1DclMzCi0tLS0tRU5EIFBHUCBQUklWQVRFIEtFWSBCTE9DSy0tLS0t
kind: Secret
metadata:
  name: sops-gpg-master
```

### Configure encryption for the entire Workload Cluster

```sh
$ kubectl gs gitops add enc --generate \
--management-cluster demomc \
--organization demoorg \
--workload-cluster demowc \
--target / \
--local-path /tmp/myrepo \
--dry-run

/tmp/myrepo/management-clusters/demomc/.sops.keys/demowc.48ebcef6d323ec166b3e9ab883efeec221b4b4ed.asc
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GopenPGP 2.4.8
Comment: https://gopenpgp.org

xjMEYvPmjRYJKwYBBAHaRw8BAQdAlap77pHZzU3bwe+AmLLNs/9/n8Jy8KSjLNRb
zdKF0hzNImRlbW93YyBXb3JrbG9hZCBDbHVzdGVyIGVuY3J5cHRpb27CjAQTFggA
PgUCYvPmjQmQg+/uwiG0tO0WIQRI68720yPsFms+mriD7+7CIbS07QIbAwIeAQIZ
AQMLCQcCFQgDFgACAiIBAABIHQEA2RN/7/ITFeXfGtGxXVmt6E7PQh8JKNeTPJ2u
5euVPMgBAIDKwqyRu+XaadshmA9NQEa07/5bnxUixDQUmCdRQ4cMzjgEYvPmjRIK
KwYBBAGXVQEFAQEHQOrJ9CvljPL8LcXFoNAOnPgDwDUHzoQ7SHnjbYzTDgAUAwEK
CcJ4BBgWCAAqBQJi8+aNCZCD7+7CIbS07RYhBEjrzvbTI+wWaz6auIPv7sIhtLTt
AhsMAADNaAD9EI2W5kaaGpNmnO+3W8vYhWTvAV5J3lxPvrwGii6ltkQA/Axr5/yh
pZ90eVvAUNZWDSWqRbjWgVT0wZBiESr7iMgN
=Qka0
-----END PGP PUBLIC KEY BLOCK-----

/tmp/myrepo/management-clusters/demomc/secrets/demowc.gpgkey.enc.yaml
apiVersion: v1
data:
  demowc.48ebcef6d323ec166b3e9ab883efeec221b4b4ed.asc: LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQpWZXJzaW9uOiBHb3BlblBHUCAyLjQuOApDb21tZW50OiBodHRwczovL2dvcGVucGdwLm9yZwoKeFZnRVl2UG1qUllKS3dZQkJBSGFSdzhCQVFkQWxhcDc3cEhaelUzYndlK0FtTExOcy85L244Snk4S1NqTE5SYgp6ZEtGMGh3QUFQOXdGQUJ5a0d2azZaVnczQ3hyVzVITVBkbW8xUDE2K21adEtablJibU1HM3hJTXpTSmtaVzF2CmQyTWdWMjl5YTJ4dllXUWdRMngxYzNSbGNpQmxibU55ZVhCMGFXOXV3b3dFRXhZSUFENEZBbUx6NW8wSmtJUHYKN3NJaHRMVHRGaUVFU092Tzl0TWo3QlpyUHBxNGcrL3V3aUcwdE8wQ0d3TUNIZ0VDR1FFREN3a0hBaFVJQXhZQQpBZ0lpQVFBQVNCMEJBTmtUZisveUV4WGwzeHJSc1YxWnJlaE96MElmQ1NqWGt6eWRydVhybFR6SUFRQ0F5c0tzCmtidmwybW5iSVpnUFRVQkd0Ty8rVzU4VklzUTBGSmduVVVPSERNZGRCR0x6NW8wU0Npc0dBUVFCbDFVQkJRRUIKQjBEcXlmUXI1WXp5L0MzRnhhRFFEcHo0QThBMUI4NkVPMGg1NDIyTTB3NEFGQU1CQ2drQUFQOWFNK2dNMkVROAp4L0NlU1dwRUVlL3JaaG8renhYU0pibzk3V2taUEwyeUNBL0J3bmdFR0JZSUFDb0ZBbUx6NW8wSmtJUHY3c0loCnRMVHRGaUVFU092Tzl0TWo3QlpyUHBxNGcrL3V3aUcwdE8wQ0d3d0FBTTFvQVAwUWpaYm1ScG9hazJhYzc3ZGIKeTlpRlpPOEJYa25lWEUrK3ZBYUtMcVcyUkFEOERHdm4vS0dsbjNSNVc4QlExbFlOSmFwRnVOYUJWUFRCa0dJUgpLdnVJeUEwPQo9WTNsSQotLS0tLUVORCBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQ==
kind: Secret
metadata:
  name: sops-gpg-demowc

/tmp/myrepo/management-clusters/demomc/organizations/demoorg/workload-clusters/demowc.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demomc-clusters-demowc
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-demowc
  interval: 1m
  path: ./management-clusters/demomc/organizations/demoorg/workload-clusters/demowc
  postBuild:
    substitute:
      cluster_name: demowc
      cluster_release: 0.13.0
      default_apps_release: 0.6.0
      organization: demoorg
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: gitops-demo
  timeout: 2m

/tmp/myrepo/.sops.yaml
creation_rules:
- encrypted_regex: ^(data|stringData)$
  path_regex: management-clusters/demomc/organizations/demoorg/workload-clusters/demowc/.*\.enc\.yaml
  pgp: 48ebcef6d323ec166b3e9ab883efeec221b4b4ed
```

### Trying to configure the entire MC_NAME directory

```sh
$ kubectl gs gitops add enc --generate \
--management-cluster demomc \
--local-path /tmp/myrepo \
--target / \
--dry-run
Error: Invalid flags: --target must not be set to '/' when used with Management Cluster or Organization only
exit status 1
```

This is to prevent SOPS from configuring everything under the `management-clusters/demomc/*\.enc\.yaml` including Workload Clusters stuff. Same goes for the Organization.

```sh
$ kubectl gs gitops add enc --generate \
--management-cluster demomc \
--organization demoorg \
--local-path /tmp/myrepo \
--target / \
--dry-run
Error: Invalid flags: --target must not be set to '/' when used with Management Cluster or Organization only
exit status 1
```
**Note**: in addition to this, when user tries to escape the requested layer, for example `management-clusters/MC_NAME`, when only `--management-cluster MC_NAME` flag is used, by setting target to `organizations/ORG_NAME/` for example, then the command will restore the default `secrets/` target to prevent misconfiguration of Flux.

### CODE REVIEW

**Comment by marians** [comment]
Hi @ljakimczuk ! I'd love to give you thorough feedback on this PR. Or rather: make sure that you get UX feedback from someone. Personally I don't even understand a lot about SOPS.

Would it be possible for you to host a little session where you give some context and demo? The next SIG UX sync is in two weeks. So I guess it would be better to make it separate.

**Comment by marians** [comment]
This Friday we have a WG GitOps UX call. That would be a good option I think.

**Comment by ljakimczuk** [comment]
Hey @marians, good idea, the WG GitOps UX works for me, we can discuss it there 👍

**Review by mproffitt — APPROVED** [review]

**Review by mproffitt — APPROVED** [review]

**Review by kubasobon — APPROVED** [review]
Thank you for keeping it readable. LGTM

**Review by kubasobon — APPROVED** [review]
LGTM. Good job! Let's not invest more time here to make it _perfecter_ :sparkles:

**Pull request merged**
